# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac03ec2a13925e3a34db2e12d8e6932abb3f0e3a1980b8d03515b54982a6f9585bc8e24fc85a6f247b1a70117d21ff7080b5b5d2de65522aa397aa1f13932fd

test:
  secret_key_base: f0777ade42fd69a5c2e4931f5a4334046c580a72c3ce98c99f190c8188ca45641702bf16c50b90407a6ce9b6e1e0ce84bf6dc9a9b09ac2dc988366e14f13defb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
